apiVersion: v1
kind: SAMLServiceProvider
metadata:
  name: "New Test App"
  environment: "dev"
  description: "Test description"
spec:
  entityId: "api://new-test-app"
  assertionConsumerServiceUrl: "https://new-test.com/acs"
  singleLogoutServiceUrl: "https://new-test.com/logout"
  claims:
    - name: "email"
      source: "user"
  groupAssignments:
    - groupId: "group-guid"
