applications:
  - name: "Test SAML App"
    identifier_uris:
      - "api://test-saml-app"
    reply_urls:
      - "https://test-app.com/acs"
    sign_on_url: "https://test-app.com/login"
    logout_url: "https://test-app.com/logout"
    owners:
      - "00000000-0000-0000-0000-000000000000"
